// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJ5k78ejBD1_VfHU_ptJyhWHgOdzAApvs',
    appId: '1:917798129834:web:ed0352d104f0a6da7400d3',
    messagingSenderId: '917798129834',
    projectId: 'pullebyte-418',
    authDomain: 'pullebyte-418.firebaseapp.com',
    storageBucket: 'pullebyte-418.appspot.com',
    measurementId: 'G-GMKL3HB6E7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUzo_Wglk4tEHzzPkoTsBtbR79PBih4jQ',
    appId: '1:917798129834:android:603355c271c569197400d3',
    messagingSenderId: '917798129834',
    projectId: 'pullebyte-418',
    storageBucket: 'pullebyte-418.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_ip3ydjsgMqb6bQmskjOivGQ8xzgbAlI',
    appId: '1:917798129834:ios:8e505a8b4d0b7edb7400d3',
    messagingSenderId: '917798129834',
    projectId: 'pullebyte-418',
    storageBucket: 'pullebyte-418.appspot.com',
    iosBundleId: 'com.example.pullebyte',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_ip3ydjsgMqb6bQmskjOivGQ8xzgbAlI',
    appId: '1:917798129834:ios:8e505a8b4d0b7edb7400d3',
    messagingSenderId: '917798129834',
    projectId: 'pullebyte-418',
    storageBucket: 'pullebyte-418.appspot.com',
    iosBundleId: 'com.example.pullebyte',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCJ5k78ejBD1_VfHU_ptJyhWHgOdzAApvs',
    appId: '1:917798129834:web:02f10281e90704a77400d3',
    messagingSenderId: '917798129834',
    projectId: 'pullebyte-418',
    authDomain: 'pullebyte-418.firebaseapp.com',
    storageBucket: 'pullebyte-418.appspot.com',
    measurementId: 'G-5SZHZB5ZBL',
  );

}